### PR TITLE
Support block-readable entries

### PR DESCRIPTION
**Pull request by ekinanp**
Signed-off-by: Enis Inan <enis.inan@puppet.com>

### CODE REVIEW

**Comment by ekinanp** [comment]
Blocked on https://github.com/puppetlabs/wash/pull/641 and a Wash release. The latter explains the CI failures.

**Review by MikaelSmith — APPROVED** [review]

**Comment by MikaelSmith** [comment]
Not sure why we didn't finish this. Was waiting on a Wash release maybe?

**Comment by ekinanp** [comment]
Oh yeah, probably. I'll re-kick the job.

**Comment by ekinanp** [comment]
Ah yeah, we need to update the Wash version used by CI. That's why this was failing. Another good reason for version-agnostic tars.

I'll do the update after this week's release since it'll be easier.

**Comment by MikaelSmith** [comment]
I'd rather continue to specify a specific version. Makes CI reproducible.

**Pull request merged**
